### ISSUE TITLE
Errant SPACE being added to some issues markdown, breaking how it's displayed in Confluence.

### ISSUE THREAD

**Issue by SheriffHobo** [indeedeng/Mariner#87] opened 2021-08-24 19:05 UTC
From time to time an issue is returned with an extra SPACE twixt two characters at the beginning of the markdown, after the first open brace '[', this space causes the layout to break for that issue. Example;

>>|[ (Bug): Derived constructors should not be allowed to return primitive values|https://github.com/babel/babel/issues/13566]|38 days|<<

The ask: Run all issues through a filter to remove any extra space from that particular position.

**Comment by kevindigo** [comment] 2021-10-11 22:33
If we had a good way to reproduce this, I might leave it open (for as long as we continue to offer confluence output. But since we don't, I'll Close it. If someone else runs into the same problem later, they can report it as a new issue. 

Thanks for helping keep our issues list cleaned up. :+1:

**Closed by kevindigo** 2021-10-11 22:33 UTC
Labels: good first issue
